import { useRef, useState } from "react";
import { apiJson, buildApiUrl } from "../lib/apiClient";
export type HandoffFrame = { index: number; timestamp_seconds: number; object_key: string; sha256: string };
export type Handoff = { frame_index: number; confirmed: boolean };
export function HandoffPanel({ jobId, order, attempt, frames, selection, locked, paused, onChanged }: { jobId: string; order: number; attempt: number; frames?: HandoffFrame[]; selection?: Handoff; locked: boolean; paused?: boolean; onChanged: () => void }) {
  const [busy, setBusy] = useState(false); const inFlight = useRef(false); const [error, setError] = useState("");
  const act = async (frame?: number, proceed = false) => { if (inFlight.current) return; inFlight.current = true; setBusy(true); setError(""); try { await apiJson('/scene-video-jobs/' + encodeURIComponent(jobId) + '/scenes/' + order + '/handoff' + (frame === undefined ? '/prepare' : ''), { method: 'POST', body: frame === undefined ? undefined : { frame, continue: proceed } }); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save continuity frame.'); } finally { inFlight.current = false; setBusy(false); } };
  return <section aria-label="Continuity handoff" className="mt-4 space-y-3 rounded border border-blue-200 bg-blue-50 p-4"><h4 className="font-semibold">Continuity frame for next scene</h4><p className="text-sm">Suggested ending frame is selected. Change it if another frame shows the resulting state more clearly.</p>
    {frames?.length ? <div className="flex gap-2 overflow-x-auto">{frames.map(frame => <button type="button" disabled={busy || locked} aria-pressed={selection?.frame_index === frame.index} onClick={() => void act(frame.index)} key={frame.index} className={"shrink-0 rounded border-2 p-1 " + (selection?.frame_index === frame.index ? "border-blue-700" : "border-transparent")}><img className="h-24 w-36 object-contain" src={buildApiUrl('/scene-video-jobs/' + encodeURIComponent(jobId) + '/scenes/' + order + '/attempts/' + attempt + '/handoff/' + frame.index)} alt={"Handoff at " + frame.timestamp_seconds.toFixed(2) + " seconds"} /><span>{frame.timestamp_seconds.toFixed(2)}s {selection?.frame_index === frame.index ? '✓ selected' : ''}</span></button>)}</div> : <button type="button" disabled={busy} onClick={() => void act()} className="rounded border px-3 py-2">Prepare continuity frames</button>}
    {selection && !locked && <button type="button" disabled={busy} onClick={() => void act(selection.frame_index, true)} className="rounded bg-blue-800 px-4 py-2 text-white">{paused ? 'Save handoff (production paused)' : 'Continue with selected frame'}</button>}
    {locked && <p className="text-sm">Saved frame is bound to the next scene’s generation.</p>}{error && <p role="alert" className="text-red-700">{error}</p>}
  </section>;
}
export function TransitionComparison({ previousUrl, openingUrl, previousExit, currentEntry, openingSeconds }: { previousUrl: string; openingUrl: string; previousExit?: string; currentEntry?: string; openingSeconds: number }) { return <section aria-label="Transition comparison" className="mt-4 rounded border border-slate-300 p-4"><h4 className="font-semibold">Transition review</h4><div className="mt-3 grid gap-4 sm:grid-cols-2"><div><h5>Previous scene handoff</h5><img className="mt-2 w-full rounded" src={previousUrl} alt="Previous accepted handoff" /><p className="mt-2 text-sm">Ends: {previousExit}</p></div><div><h5>Current scene opening · {openingSeconds.toFixed(2)}s</h5><img className="mt-2 w-full rounded" src={openingUrl} alt="Current scene opening" /><p className="mt-2 text-sm">Starts: {currentEntry}</p></div></div></section>; }
