import { useState, type FormEvent } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { apiJson } from "../lib/apiClient";
import { primary } from "./videoProduct";

type Item = {job_id:string;title:string;status:string;scene_count:number;accepted_count:number;started:boolean;paused:boolean;failure?:string;scene_seconds:number;runs:{scene_order:number;status:string}[]};
export type AutopilotData = {server_now:string;available:boolean;runtime_notice:string;capabilities:{aspect_ratios:string[];native_seconds:number;max_scenes:number};scheduler:{enabled:boolean;configured_submission_cap:number;submissions_this_window:number;next_eligible_at?:string;provider_block_reason?:string;active_run?:string;current_project?:string;queue:Item[]}};
const labels:Record<string,string>={planning:"Planning",ready:"Ready for Gemini",generating:"Generating",completed:"Completed by Gemini Autopilot",needs_attention:"Needs attention",skipped:"Skipped",login_required:"Needs login",human_action_required:"Needs manual attention",limit_reached:"Gemini usage limit reached",weekly_limit:"Gemini weekly limit reached",temporary_capacity:"Gemini temporarily busy",safety_cap:"Window safety cap reached",ui_changed:"Gemini interface needs attention",ui_unavailable:"Gemini interface unavailable",browser_unavailable:"Gemini browser unavailable",browser_session_unavailable:"Gemini account is busy",generation_in_progress:"Gemini is still generating",visible_browser_required:"Open the Gemini browser",local_storage_critical:"Paused \u2014 local storage critically low",reconciliation_required:"Submission needs reconciliation"};
const text=(s:string)=>labels[s]??s.replaceAll("_"," ");
export function GeminiAutopilotPage(){
 const query=useQuery({queryKey:["geminiAutopilot"],queryFn:()=>apiJson<AutopilotData>("/gemini-autopilot"),refetchInterval:2000});
 const [form,setForm]=useState(false),[title,setTitle]=useState(""),[idea,setIdea]=useState(""),[scenes,setScenes]=useState(2),[aspect,setAspect]=useState("16:9"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[cap,setCap]=useState<number|undefined>(undefined);
 async function control(path:string,body?:unknown){if(busy)return;setBusy(true);setError("");try{await apiJson(path,{method:"POST",body});await query.refetch();}catch(e){setError(e instanceof Error?e.message:"Could not update queue");}finally{setBusy(false);}}
 async function add(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");try{await apiJson("/gemini-autopilot/queue",{method:"POST",body:{title,idea,scene_count:scenes,aspect_ratio:aspect}});setForm(false);setTitle("");setIdea("");await query.refetch();}catch(e){setError(e instanceof Error?e.message:"Could not add video");}finally{setBusy(false);}}
 const data=query.data,s=data?.scheduler;const waiting=Boolean(s?.next_eligible_at&&Date.parse(s.next_eligible_at)>Date.parse(data?.server_now??"" ));
 return <div className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-3xl font-semibold">Gemini Autopilot</h2><p className="mt-2 text-slate-600">Queue ideas and return to finished videos.</p></div><button className={primary} disabled={!data?.available||busy} onClick={()=>setForm(true)}>+ Queue Video</button></header>

 {query.isLoading&&<p role="status">Loading Gemini queue…</p>}{query.isError&&<p role="alert">{query.error.message}</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}
 {data&&s&&<><section className="space-y-3 rounded-xl border bg-white p-6" aria-label="Autopilot status"><p className="text-xl font-semibold">{!data.available?"Gemini Autopilot is not configured":!s.enabled?"Autopilot paused":s.provider_block_reason?text(s.provider_block_reason):s.active_run?"Currently generating":waiting?"Waiting for next window":"Autopilot enabled"}</p><p>{s.submissions_this_window} / {s.configured_submission_cap} submissions in this window · user safety cap</p>{s.next_eligible_at&&<p>Next eligibility: <time dateTime={s.next_eligible_at}>{new Date(s.next_eligible_at).toLocaleString()}</time></p>}<p className="text-sm text-slate-600">{data.runtime_notice}</p><button disabled={busy||!data.available} className="rounded border px-4 py-2" onClick={()=>void control(`/gemini-autopilot/control/${s.enabled?"pause":"resume"}`)}>{s.enabled?"Pause Autopilot":"Resume Autopilot"}</button><p className="text-xs text-slate-500">Pausing lets the current generation finish. Planning can continue while waiting.</p></section>
 {form&&<form onSubmit={event=>void add(event)} className="space-y-4 rounded-xl border bg-white p-6" aria-label="Queue Video"><h3 className="text-xl font-semibold">Queue Video</h3><label className="block">Title<input className="mt-1 block w-full rounded border p-3" value={title} onChange={e=>setTitle(e.target.value)} maxLength={80}/></label><label className="block">Idea<textarea required className="mt-1 block w-full rounded border p-3" value={idea} onChange={e=>setIdea(e.target.value)} maxLength={12000} rows={4}/></label><div className="flex flex-wrap gap-4"><label>Scenes<input aria-label="Scenes" type="number" min={1} max={data.capabilities.max_scenes} value={scenes} onChange={e=>setScenes(Number(e.target.value))} className="ml-2 w-20 rounded border p-2"/></label><label>Aspect<select className="ml-2 rounded border p-2" value={aspect} onChange={e=>setAspect(e.target.value)}>{data.capabilities.aspect_ratios.map(a=><option key={a}>{a}</option>)}</select></label></div><p className="text-sm text-slate-600">Provider native video duration: {data.capabilities.native_seconds} sec observed. Later scenes use the previous ending image as a continuity reference.</p><div className="flex gap-3"><button disabled={busy} className={primary} type="submit">Add to Queue</button><button type="button" onClick={()=>setForm(false)} className="rounded border p-3">Cancel</button></div></form>}
 <section aria-label="Video queue" className="space-y-3"><h3 className="text-xl font-semibold">Video queue</h3>{s.queue.length===0&&<p className="rounded-xl border bg-white p-8">Your queue is empty. Add an idea to begin.</p>}<ol className="space-y-3">{s.queue.map((item,index)=><li key={item.job_id} className="space-y-3 rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><Link to={`/scene-jobs/${item.job_id}`} className="text-xl font-semibold text-blue-800">{index+1}. {item.title}</Link><span>{item.paused&&item.status!=="skipped"?"Project paused":text(item.status)}</span></div><p>{item.accepted_count} / {item.scene_count} scenes produced{item.status==="generating"&&item.runs.at(-1)?` · Scene ${item.runs.at(-1)?.scene_order}`:""}</p>{item.failure&&<p className="text-amber-800">{text(item.failure)}</p>}{item.status==="completed"&&<p className="text-sm">Creative quality has not been human reviewed.</p>}{!["completed","skipped"].includes(item.status)&&<div className="flex flex-wrap gap-2">{!item.started&&item.status!=="generating"&&<><button disabled={busy||index===0} onClick={()=>void control(`/gemini-autopilot/items/${item.job_id}/up`)} className="rounded border p-2" aria-label={`Move ${item.title} up`}>↑</button><button disabled={busy||index===s.queue.length-1} onClick={()=>void control(`/gemini-autopilot/items/${item.job_id}/down`)} className="rounded border p-2" aria-label={`Move ${item.title} down`}>↓</button><button disabled={busy} onClick={()=>void control(`/gemini-autopilot/items/${item.job_id}/remove`)} className="rounded border p-2">Remove</button></>}<button disabled={busy||item.status==="needs_attention"} onClick={()=>void control(`/gemini-autopilot/items/${item.job_id}/${item.paused?"resume":"pause"}`)} className="rounded border p-2">{item.paused?"Resume project":"Pause project"}</button>{item.status!=="generating"&&<button disabled={busy} onClick={()=>void control(`/gemini-autopilot/items/${item.job_id}/skip`)} className="rounded border p-2">Skip project</button>}</div>}</li>)}</ol></section>
 <details className="rounded border bg-white p-4"><summary className="cursor-pointer">Advanced settings</summary><label className="mt-4 block">Max Gemini submissions per window<input type="number" min={1} max={20} value={cap??s.configured_submission_cap} onChange={e=>setCap(Number(e.target.value))} className="ml-3 w-20 rounded border p-2"/></label><button disabled={busy} className="mt-3 rounded border p-2" onClick={()=>void control("/gemini-autopilot/control/settings",{configured_submission_cap:cap??s.configured_submission_cap})}>Save safety cap</button><p className="mt-3 text-sm">The five-hour window is a fallback. An explicit Gemini reset time takes precedence. Remaining credits are unknown.</p></details><details className="rounded border bg-white p-4"><summary className="cursor-pointer">Diagnostics</summary><button disabled={busy} className="mt-3 rounded border p-2" onClick={()=>{if(busy)return;setBusy(true);void apiJson<{status:string}>("/scene-video-providers/gemini-web/readiness").then(result=>setError(`Gemini readiness: ${text(result.status)}`)).catch(e=>setError(e instanceof Error?e.message:"Readiness unavailable")).finally(()=>setBusy(false));}}>Check Gemini readiness</button>{s.provider_block_reason==="reconciliation_required"&&<><p className="mt-3">Recover an existing result without submitting another video. The lane stays paused until you resume.</p><button disabled={busy} className="mt-3 rounded border p-2" onClick={()=>void control("/gemini-autopilot/control/recover")}>Recover existing result</button></>}<pre className="mt-4 overflow-auto text-xs">{JSON.stringify(s,null,2)}</pre></details></>}
 </div>;
}
