import { useState, type FormEvent } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { apiJson } from "../lib/apiClient";
import { primary } from "./videoProduct";
export function CreateSceneVideoPage() {
 const navigate=useNavigate();
 const options=useQuery({queryKey:["videoCreationOptions"],queryFn:()=>apiJson<{standard_available:boolean;scene_seconds:number;initial_keyframe_enabled?:boolean;capabilities?:{aspect_ratios:string[];scene_durations:number[];min_scene_count:number;max_scene_count:number}}>("/scene-video-options")});
 const [title,setTitle]=useState(''),[topic,setTopic]=useState(''),[count,setCount]=useState(2),[aspect,setAspect]=useState('16:9'),[audio,setAudio]=useState('clip_native');
 const [continuity,setContinuity]=useState('chained_frames'),[review,setReview]=useState('ai_assisted'),[reference,setReference]=useState('none'),[character,setCharacter]=useState('');
 const [selectedSeconds,setSelectedSeconds]=useState<number|undefined>(undefined);
 const seconds=selectedSeconds??options.data?.scene_seconds??8;
 const durations=options.data?.capabilities?.scene_durations??(options.data?[options.data.scene_seconds]:[]);
 const counts=Array.from({length:options.data?.capabilities?.max_scene_count??4},(_,i)=>i+1);
 const [opening,setOpening]=useState<boolean|undefined>(undefined);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function create(event:FormEvent<HTMLFormElement>) {event.preventDefault();if(busy)return;setBusy(true);setError('');try {const result=await apiJson<{job_id:string}>("/scene-video-jobs",{method:"POST",body:{preset:"standard_video",title,topic,character,scene_count:count,aspect_ratio:aspect,scene_seconds:seconds,audio_policy:audio,continuity_mode:continuity,review_policy:review,reference_mode:reference,opening_image_required:(opening??options.data?.initial_keyframe_enabled??false)&&review==='ai_assisted'&&reference==='none'}});navigate(`/scene-jobs/${result.job_id}`);}catch(cause){setError(cause instanceof Error?cause.message:'Could not prepare storyboard.');}finally{setBusy(false);}}
 const field='mt-1 w-full rounded-lg border border-slate-300 p-3';
 return <div className="mx-auto max-w-2xl space-y-5"><div><h2 className="text-3xl font-semibold">New Video</h2><p className="mt-2 text-slate-600">Standard Video · Describe your idea, review the storyboard, then start production.</p></div><form onSubmit={event=>void create(event)} className="space-y-5 rounded-xl border bg-white p-6">
 <label className="block font-medium">Video title <span className="text-sm font-normal text-slate-500">(optional)</span><input className={field} maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/></label>
 <label className="block font-medium">Idea / story<textarea className={field} required rows={5} value={topic} onChange={e=>setTopic(e.target.value)} placeholder="A small robot finds a glowing crystal and brings an abandoned workshop to life."/></label>
 <div className="grid gap-4 sm:grid-cols-2"><label className="block font-medium">Scene count<select className={field} value={count} onChange={e=>setCount(Number(e.target.value))}>{counts.map(n=><option key={n} value={n}>{n} {n===1?'scene':'scenes'}</option>)}</select></label><label className="block font-medium">Aspect ratio<select className={field} value={aspect} onChange={e=>setAspect(e.target.value)}>{(options.data?.capabilities?.aspect_ratios??['16:9','9:16']).map(value=><option key={value}>{value}</option>)}</select></label>
 <label className="block font-medium">Scene length<select className={field} disabled={!options.data||durations.length===0} aria-label="Scene length" value={seconds} onChange={e=>setSelectedSeconds(Number(e.target.value))}>{durations.map(n=><option key={n} value={n}>{n} seconds</option>)}</select><span className="text-xs font-normal text-slate-500">Length per scene.</span></label><label className="block font-medium">Audio<select className={field} value={audio} onChange={e=>setAudio(e.target.value)}><option value="clip_native">Native audio</option><option value="silent">Silent</option></select></label></div>
 <p aria-label="Approx. video length" className="rounded bg-blue-50 p-3">Approx. video length: {count} scenes × {seconds} sec - Up to ~{count*seconds} sec before transitions/normalization.</p>
 <details className="rounded border p-4"><summary className="cursor-pointer font-medium">Advanced settings</summary><div className="mt-4 space-y-4"><p className="text-sm text-slate-600">Flow Web automation is configured by the app. Manual Flow recovery remains available in production details.</p><label className="block"><input type="checkbox" checked={opening??options.data?.initial_keyframe_enabled??false} disabled={review!=='ai_assisted'||reference!=='none'} onChange={e=>setOpening(e.target.checked)}/> Review an opening image before the first video</label><label className="block">Character / subject direction<input className={field} value={character} onChange={e=>setCharacter(e.target.value)}/></label><label className="block">Continuity<select className={field} value={continuity} onChange={e=>{setContinuity(e.target.value);if(e.target.value==='chained_frames'){setReview('ai_assisted');setReference('none');}}}><option value="chained_frames">Continue from accepted ending frames</option><option value="independent">Independent scenes</option></select></label><label className="block">Review mode<select disabled={continuity==='chained_frames'} className={field} value={review} onChange={e=>setReview(e.target.value)}><option value="ai_assisted">AI assisted · you decide</option><option value="off">Off · assemble imported scenes</option></select></label><label className="block">Reference mode<select disabled={continuity==='chained_frames'} className={field} value={reference} onChange={e=>setReference(e.target.value)}><option value="none">No separate reference image</option><option value="provider_generated">Configured image provider</option></select></label></div></details>
 {options.isError&&<p role="alert">{options.error.message}</p>}{options.data&&!options.data.standard_available&&<p role="alert">Standard Video is unavailable. Configure the existing Flow automation path before creating a video.</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}
 <button className={primary} disabled={busy||!topic.trim()||!options.data?.standard_available}>{busy?'Preparing…':'Generate Storyboard'}</button><p className="text-xs text-slate-500">You will review the storyboard before any video generation starts.</p>
 </form></div>;
}
