import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { apiJson } from "../lib/apiClient";
import { OpeningImagePanel, OpeningComparison, OpeningProviderSettings } from "./OpeningImagePanel";
vi.mock("../lib/apiClient",async original=>({...await original<typeof import("../lib/apiClient")>(),apiJson:vi.fn()}));
beforeEach(()=>{vi.mocked(apiJson).mockReset();vi.mocked(apiJson).mockResolvedValue({});});
const props={jobId:'job',opening:{required:true,versions:[{version:2}]},imageUrl:'/scene-video-jobs/job/opening-images/2',expected:'Lantern starts off.',action:'review_opening_image',onChanged:vi.fn()};
it('shows initial-state review without accepting or generating a video',()=>{render(<OpeningImagePanel {...props}/>);expect(screen.getByAltText('Scene 1 opening image')).toBeVisible();expect(screen.getByText('Lantern starts off.')).toBeVisible();expect(screen.getByRole('button',{name:'Use This Image'})).toBeVisible();expect(screen.getByRole('button',{name:'Generate Another'})).toBeVisible();expect(screen.queryByRole('button',{name:'Accept Scene'})).not.toBeInTheDocument();expect(apiJson).not.toHaveBeenCalled();});
it('requests another still only on deliberate click',async()=>{render(<OpeningImagePanel {...props}/>);await userEvent.click(screen.getByRole('button',{name:'Generate Another'}));expect(apiJson).toHaveBeenCalledTimes(1);expect(apiJson).toHaveBeenCalledWith('/scene-video-jobs/job/opening-image/generate',{method:'POST',body:undefined});});
it('approves the shown version without submitting any video',async()=>{render(<OpeningImagePanel {...props}/>);await userEvent.click(screen.getByRole('button',{name:'Use This Image'}));expect(apiJson).toHaveBeenCalledTimes(1);expect(apiJson).toHaveBeenCalledWith('/scene-video-jobs/job/opening-image/approve',{method:'POST',body:{version:2}});expect(props.onChanged).toHaveBeenCalled();});
it('waits during image preparation without presenting invalid approval',()=>{render(<OpeningImagePanel {...props} imageUrl={undefined} action="wait_for_opening_image"/>);expect(screen.getByRole('status')).toHaveTextContent('Video generation waits');expect(screen.queryByRole('button',{name:'Use This Image'})).not.toBeInTheDocument();expect(apiJson).not.toHaveBeenCalled();});
it('reconciles uncertain image submission through the existing project',async()=>{render(<OpeningImagePanel {...props} action="recover_opening_image" opening={{required:true,runs:[{run_id:'r',status:'human_action_required',submission_intent:true,evidence:{project_id:'4c7b2542-cbe6-4703-b837-ac40d523f339'}}]}}/>);expect(screen.getByText(/before any deliberate retry/)).toBeVisible();expect(screen.getByRole("link",{name:"Open Flow to Check"})).toHaveAttribute("href","https://flow.google.com/project/4c7b2542-cbe6-4703-b837-ac40d523f339");await userEvent.click(screen.getByRole('button',{name:'Recover Opening Image'}));expect(apiJson).toHaveBeenCalledWith('/scene-video-jobs/job/opening-image/resume',{method:'POST',body:undefined});});
it('shows approved opening beside generated opening',()=>{render(<OpeningComparison approvedUrl="/approved.png" generatedUrl="http://localhost:8080/generated.jpg"/>);expect(screen.getByAltText('Approved opening')).toHaveAttribute('src',expect.stringContaining('/approved.png'));expect(screen.getByAltText('Generated opening')).toHaveAttribute('src','http://localhost:8080/generated.jpg');});

it('requires explicit no-image and possible-charge acknowledgment before clearing uncertainty',async()=>{render(<OpeningImagePanel {...props} action="recover_opening_image" opening={{required:true,runs:[{run_id:'image-run',status:'human_action_required',submission_intent:true}]}}/>);await userEvent.click(screen.getByText('If Flow has no image'));const confirm=screen.getByRole('button',{name:'Confirm No Image'});expect(confirm).toBeDisabled();await userEvent.click(screen.getByRole('checkbox'));await userEvent.click(confirm);expect(apiJson).toHaveBeenCalledTimes(1);expect(apiJson).toHaveBeenCalledWith('/scene-video-jobs/job/opening-image/reconcile-no-result',{method:'POST',body:{run_id:'image-run',acknowledge_possible_charge:true}});});

it('restores a completed ChatGPT still with no reload submission and hides provider in basic review',()=>{render(<OpeningImagePanel {...props} opening={{...props.opening,provider:'chatgpt_web',runs:[{run_id:'fresh',provider:'chatgpt_web',status:'completed',submission_intent:true}],versions:[{version:2,media_check:'passed',width:1600,height:900}]}}/>);expect(screen.getByText('Opening image ready')).toBeVisible();expect(screen.queryByText(/chatgpt_web/)).not.toBeInTheDocument();expect(apiJson).not.toHaveBeenCalled();});
it('blocks approval for a materially wrong aspect while permitting deliberate Generate Another',()=>{render(<OpeningImagePanel {...props} opening={{...props.opening,provider:'chatgpt_web',versions:[{version:2,media_check:'aspect_mismatch',width:1024,height:1024}]}}/>);expect(screen.getByRole('button',{name:'Use This Image'})).toBeDisabled();expect(screen.getByRole('alert')).toHaveTextContent('aspect ratio');expect(screen.getByRole('button',{name:'Generate Another'})).toBeEnabled();});
it('shows provider only in diagnostics and switches without generating',async()=>{render(<OpeningProviderSettings jobId="job" opening={{required:true}} onChanged={props.onChanged}/>);expect(screen.getByText('Opening image provider: flow_web')).toBeVisible();const switchButton=screen.getByRole('button',{name:'Use ChatGPT Web for Opening Images'});expect(switchButton).toBeDisabled();await userEvent.click(screen.getByRole('checkbox'));await userEvent.click(switchButton);expect(apiJson).toHaveBeenCalledTimes(1);expect(apiJson).toHaveBeenCalledWith('/scene-video-jobs/job/opening-image/provider',{method:'POST',body:{provider:'chatgpt_web',confirm_no_active_generation:true}});});
it('offers no-submit recovery of an uncertain ChatGPT image',()=>{render(<OpeningImagePanel {...props} action="recover_opening_image" opening={{required:true,provider:'chatgpt_web',runs:[{run_id:'uncertain',status:'human_action_required',submission_intent:true,failure:'timeout'}]}}/>);expect(screen.getByRole('button',{name:'Recover Opening Image'})).toBeEnabled();expect(screen.queryByRole('button',{name:'Generate Another'})).not.toBeInTheDocument();expect(screen.getByRole('link',{name:'Open Image Session'})).toHaveAttribute('href','https://chatgpt.com/');expect(apiJson).not.toHaveBeenCalled();});
it('allows a manual image upload when preparation is unavailable',async()=>{const fetchMock=vi.fn().mockResolvedValue({ok:true});vi.stubGlobal('fetch',fetchMock);try{render(<OpeningImagePanel {...props} imageUrl={undefined} action="prepare_opening_image" opening={{required:true,provider:'chatgpt_web'}}/>);await userEvent.click(screen.getByText('Upload Opening Image'));await userEvent.upload(screen.getByLabelText('Opening image file'),new File(['png'],'opening.png',{type:'image/png'}));await userEvent.click(screen.getByRole('button',{name:'Upload for Review'}));expect(fetchMock).toHaveBeenCalledTimes(1);expect(fetchMock.mock.calls[0][0]).toContain('/opening-image/upload');expect(apiJson).not.toHaveBeenCalled();}finally{vi.unstubAllGlobals();}});

it('shows stopped preparation with an explicit retry and no background generation',async()=>{render(<OpeningImagePanel {...props} imageUrl={undefined} action="recover_opening_image" opening={{required:true,provider:'chatgpt_web',runs:[{run_id:'stale',status:'failed',submission_intent:false,failure:'opening_execution_stopped'}]}}/>);expect(screen.getByText(/Opening image generation stopped/)).toBeVisible();expect(screen.queryByText(/Preparing the opening image/)).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Try Again'}));expect(apiJson).toHaveBeenCalledWith('/scene-video-jobs/job/opening-image/generate',{method:'POST',body:undefined});});
