import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { apiJson } from "../lib/apiClient";
import { ProjectStorage, StoragePage, StorageWarning, type StorageData } from "./StoragePage";
vi.mock("../lib/apiClient",()=>({apiJson:vi.fn()}));
beforeEach(()=>vi.mocked(apiJson).mockReset());afterEach(()=>{cleanup();vi.restoreAllMocks()});
const data:StorageData={local:[{path:"D:/production",total:100*1024**3,used:30*1024**3,free:70*1024**3,percent:30,status:"healthy"}],drive_status:"connected",archive_folder:"AI Video Archive",queue_count:2,settings:{automatic:true,level:"restorable",cleanup:"keep_local",warning_bytes:20*1024**3,critical_bytes:10*1024**3,reserve_bytes:2*1024**3}};
function show(node:React.ReactNode){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{node}</QueryClientProvider>)}
it.each(["not_configured","needs_connection","connected"])("shows Drive state %s and dashboard",async state=>{vi.mocked(apiJson).mockResolvedValue({...data,drive_status:state});show(<StoragePage/>);expect(await screen.findByLabelText("Local storage")).toHaveTextContent("70.00 GiB free");expect(screen.getByText("Archive queue: 2 projects")).toBeVisible();expect(screen.queryByRole("button",{name:"Connect Google Drive"})!==null).toBe(state!=="connected")});
it("fetches only the local JSON start endpoint and navigates the browser to consent",async()=>{const popup={location:{href:""},close:vi.fn()};const open=vi.spyOn(window,"open").mockReturnValue(popup as unknown as Window);const fetchSpy=vi.spyOn(window,"fetch");vi.mocked(apiJson).mockImplementation(async path=>path==="/storage"?{...data,drive_status:"needs_connection"}:{authorization_url:"https://accounts.google.com/fixture"});show(<StoragePage/>);fireEvent.click(await screen.findByRole("button",{name:"Connect Google Drive"}));await waitFor(()=>expect(popup.location.href).toBe("https://accounts.google.com/fixture"));expect(open).toHaveBeenCalledWith("about:blank","drive-oauth");expect(apiJson).toHaveBeenCalledWith("/storage/drive/connect",{method:"POST"});expect(vi.mocked(apiJson).mock.calls.every(([path])=>path.startsWith("/storage"))).toBe(true);expect(fetchSpy).not.toHaveBeenCalled()});
it.each(["warning","critical"])("shows %s disk warning",async status=>{vi.mocked(apiJson).mockResolvedValue({...data,local:[{...data.local[0],status}]});show(<StorageWarning/>);expect(await screen.findByText(status==="critical"?/New video submissions are paused/:/Low local storage/)).toBeVisible()});
it("saves storage policy and thresholds",async()=>{vi.mocked(apiJson).mockResolvedValue(data);show(<StoragePage/>);fireEvent.click(await screen.findByText("Storage Settings"));fireEvent.change(screen.getByLabelText("Archive level"),{target:{value:"full_history"}});fireEvent.click(screen.getByRole("button",{name:"Save Storage Settings"}));await waitFor(()=>expect(apiJson).toHaveBeenCalledWith("/storage/settings",{method:"POST",body:{...data.settings,level:"full_history"}}))});
it("reviews bulk inventory before queuing completed projects",async()=>{vi.mocked(apiJson).mockImplementation(async path=>path==="/storage/inventory"?{completed_projects:13,eligible_artifacts:118,eligible_bytes:200*1024**2,reclaimable_bytes:0}:data);show(<StoragePage/>);expect(screen.queryByRole("button",{name:"Archive All Completed"})).not.toBeInTheDocument();fireEvent.click(await screen.findByRole("button",{name:"Review archive inventory"}));fireEvent.click(await screen.findByRole("button",{name:"Archive All Completed"}));await waitFor(()=>expect(apiJson).toHaveBeenCalledWith("/storage/archive-all",{method:"POST",body:undefined}))});
it.each(["not_requested","uploading","failed","archived","restoring","restored","restore_failed"])("shows project storage %s",async state=>{vi.mocked(apiJson).mockResolvedValue({state,manifest:{verified:state==="archived"},artifacts:[{role:"final_video",local_object_key:"final",size:10,verified:state==="archived",local_removed:state==="archived"}],bytes_removed:0});show(<ProjectStorage id="old" onChanged={()=>{}}/>);expect(await screen.findByRole("status")).toBeVisible();if(state==="archived")expect(screen.getByRole("button",{name:"Restore & Watch"})).toBeVisible();if(state==="not_requested")expect(screen.getByRole("button",{name:"Archive Now"})).toBeVisible();if(state==="uploading")expect(screen.getByText("0 / 1 artifacts verified")).toBeVisible()});
it("queues manual archive with the same worker API",async()=>{vi.mocked(apiJson).mockResolvedValue({state:"not_requested",artifacts:[]});show(<ProjectStorage id="old" onChanged={()=>{}}/>);fireEvent.click(await screen.findByRole("button",{name:"Archive Now"}));await waitFor(()=>expect(apiJson).toHaveBeenCalledWith("/storage/projects/old/archive",{method:"POST",body:undefined}))});
it("queues restore and preserves archived project identity",async()=>{const changed=vi.fn();vi.mocked(apiJson).mockResolvedValue({state:"archived",artifacts:[{role:"final_video",local_object_key:"final",size:20,verified:true,local_removed:true}]});show(<ProjectStorage id="old" onChanged={changed}/>);fireEvent.click(await screen.findByRole("button",{name:"Restore & Watch"}));await waitFor(()=>expect(apiJson).toHaveBeenCalledWith("/storage/projects/old/restore",{method:"POST",body:undefined}));await waitFor(()=>expect(changed).toHaveBeenCalled())});
