import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiJson } from "../lib/apiClient";
import { primary } from "./videoProduct";

type Settings = { automatic:boolean; level:string; cleanup:string; warning_bytes:number; critical_bytes:number; reserve_bytes:number };
export type StorageData = { local:{path:string;total:number;used:number;free:number;percent:number;status:string}[];disk_error?:string;drive_status:string;archive_folder:string;queue_count:number;settings:Settings };
type Inventory = { completed_projects:number;eligible_artifacts:number;eligible_bytes:number;reclaimable_bytes:number };
const space=(bytes:number)=>`${(bytes/1024**3).toFixed(2)} GiB`;
const levels={final_only:"Final Only",restorable:"Restorable",full_history:"Full History"};
const policies={keep_local:"Keep local files",intermediates:"Remove verified intermediates",restorable_media:"Remove verified scenes and frames",cloud_only:"Cloud archive only (remove final video too)"};
export function StorageWarning(){
 const q=useQuery({queryKey:["storage"],queryFn:()=>apiJson<StorageData>("/storage"),refetchInterval:10000,retry:false});
 const critical=q.data?.local?.some(d=>d.status==="critical")||q.data?.disk_error;
 const warning=q.data?.local?.some(d=>d.status==="warning");
 return critical?<p role="alert" className="rounded border border-amber-400 bg-amber-50 p-3">Local storage critically low. New video submissions are paused; submitted work can finish.</p>:warning?<p role="status" className="rounded border border-amber-400 bg-amber-50 p-3">Low local storage. Completed videos are eligible for archive.</p>:null;
}
export function StoragePage(){
 const q=useQuery({queryKey:["storage"],queryFn:()=>apiJson<StorageData>("/storage"),refetchInterval:5000});
 const [draft,setDraft]=useState<Settings>(),[inventory,setInventory]=useState<Inventory>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function action(path:string,body?:unknown){setBusy(true);setError("");try{await apiJson(path,{method:"POST",body});await q.refetch();}catch(e){setError(e instanceof Error?e.message:"Storage action failed");}finally{setBusy(false);}}
 async function connect(){setBusy(true);setError("");const popup=window.open("about:blank","drive-oauth");try{const r=await apiJson<{authorization_url:string}>("/storage/drive/connect",{method:"POST"});if(popup)popup.location.href=r.authorization_url;else window.location.assign(r.authorization_url);}catch(e){popup?.close();setError(e instanceof Error?e.message:"Could not connect Drive");}finally{setBusy(false);}}
 const data=q.data,settings=draft??data?.settings;
 return <div className="space-y-5"><header><h2 className="text-3xl font-semibold">Storage</h2><p className="mt-2 text-slate-600">Keep production local and archive completed videos to your Google Drive.</p></header>{q.isLoading&&<p role="status">Loading storage…</p>}{q.isError&&<p role="alert">{q.error.message}</p>}{error&&<p role="alert">{error}</p>}
 {data&&<><section className="space-y-3 rounded-xl border bg-white p-6" aria-label="Local storage"><h3 className="text-xl font-semibold">Local</h3>{data.disk_error&&<p role="alert">{data.disk_error}</p>}{data.local.map(d=><div key={d.path}><p>{space(d.used)} / {space(d.total)} used · {space(d.free)} free</p><progress aria-label={`Disk usage ${d.path}`} value={d.percent} max={100}/><p>{d.status==="critical"?"Critically low — new generation paused":d.status==="warning"?"Low storage":"Healthy"}</p><details><summary>Filesystem details</summary><p className="break-all">{d.path}</p></details></div>)}<p className="text-sm text-slate-600">Deleting MinIO objects frees space inside Docker. Its Windows disk image may not shrink immediately.</p></section>
 <section className="space-y-3 rounded-xl border bg-white p-6" aria-label="Google Drive"><h3 className="text-xl font-semibold">Google Drive</h3><p>{data.drive_status==="connected"?"Connected":data.drive_status==="not_configured"?"OAuth Desktop client setup required":"Google Drive needs connection"}</p><p>Archive folder: {data.archive_folder}</p>{data.drive_status!=="connected"&&<button disabled={busy} className={primary} onClick={()=>void connect()}>Connect Google Drive</button>}<p>Archive queue: {data.queue_count} projects</p><p className="text-sm">The PC and backend must stay running for automatic archival.</p>{data.drive_status==="not_configured"&&<p className="text-sm">Enable Drive API in your Google Cloud project, create an OAuth Desktop app client, and place the downloaded JSON at the backend’s ignored .credentials/drive/client.json path. Then connect and approve consent in your browser.</p>}</section>
 <section className="space-y-3 rounded-xl border bg-white p-6"><h3 className="text-xl font-semibold">Completed projects</h3><button disabled={busy} className="rounded border p-3" onClick={()=>{setBusy(true);setError("");void apiJson<Inventory>("/storage/inventory").then(setInventory).catch(e=>setError(e instanceof Error?e.message:"Inventory failed")).finally(()=>setBusy(false));}}>Review archive inventory</button>{inventory&&<><p>{inventory.completed_projects} completed projects · {inventory.eligible_artifacts} local artifacts · {space(inventory.eligible_bytes)} eligible</p><p>{space(inventory.reclaimable_bytes)} reclaimable under the current policy; nothing has been removed by this inventory.</p><button disabled={busy||data.drive_status!=="connected"||inventory.completed_projects===0} className={primary} onClick={()=>void action("/storage/archive-all")}>Archive All Completed</button></>}</section>
 {settings&&<details className="rounded-xl border bg-white p-6"><summary className="cursor-pointer font-semibold">Storage Settings</summary><div className="mt-4 space-y-4"><label className="block"><input type="checkbox" checked={settings.automatic} onChange={e=>setDraft({...settings,automatic:e.target.checked})}/> Automatically archive completed projects</label><label className="block">Archive level<select className="ml-3 rounded border p-2" value={settings.level} onChange={e=>setDraft({...settings,level:e.target.value})}>{Object.entries(levels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label className="block">After verification<select className="ml-3 rounded border p-2" value={settings.cleanup} onChange={e=>setDraft({...settings,cleanup:e.target.value})}>{Object.entries(policies).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><p className="text-sm">Only artifacts included in the selected archive can be removed. Restorable keeps failed attempts outside the archive. Policies apply to newly queued projects.</p>{(["warning_bytes","critical_bytes","reserve_bytes"] as const).map(key=><label key={key} className="block">{key==="warning_bytes"?"Warning free space":key==="critical_bytes"?"Critical free space":"Working space reserve"} (GiB)<input className="ml-3 w-24 rounded border p-2" type="number" min={0} step={1} value={settings[key]/1024**3} onChange={e=>setDraft({...settings,[key]:Number(e.target.value)*1024**3})}/></label>)}<button disabled={busy} className={primary} onClick={()=>void action("/storage/settings",settings)}>Save Storage Settings</button></div></details>}</>}
 </div>;
}

type ArchiveRecord={state:string;error?:string;bytes_removed?:number;manifest?:{verified:boolean};artifacts:{role:string;local_object_key:string;size:number;verified:boolean;local_removed:boolean;intermediate?:boolean;drive_file_id?:string}[]};
const stateLabels:Record<string,string>={not_requested:"Local files",queued:"Archive queued",uploading:"Uploading to Google Drive",verifying:"Verifying archive",verified:"Archive verified",cleanup_pending:"Cleanup queued",archived:"Archived to Google Drive",failed:"Archive failed",restore_queued:"Restore queued",restoring:"Restoring local media",restored:"Local + Drive",restore_failed:"Restore failed"};
export function ProjectStorage({id,onChanged}:{id:string;onChanged:()=>void}){
 const q=useQuery({queryKey:["projectStorage",id],queryFn:()=>apiJson<ArchiveRecord>(`/storage/projects/${encodeURIComponent(id)}`),refetchInterval:3000});
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[policy,setPolicy]=useState("intermediates");
 async function action(action:string){setBusy(true);setError("");try{await apiJson(`/storage/projects/${encodeURIComponent(id)}/${action}`,{method:"POST",body:action==="cleanup"?{policy}:undefined});await q.refetch();onChanged();}catch(e){setError(e instanceof Error?e.message:"Storage action failed");}finally{setBusy(false);}}
 const r=q.data?.artifacts?q.data:undefined;const working=r&&["queued","uploading","verifying","verified","cleanup_pending","restore_queued","restoring"].includes(r.state);const missing=r?.artifacts.some(a=>a.local_removed);const verified=r?.artifacts.filter(a=>a.verified).length??0;
 return <section className="space-y-3 rounded-xl border bg-white p-6" aria-label="Project storage"><h3 className="text-xl font-semibold">Storage</h3>{q.isError&&<p role="alert">{q.error.message}</p>}{error&&<p role="alert">{error}</p>}{r&&<><p role="status">{stateLabels[r.state]??r.state}</p>{r.error&&<p role="alert">{r.error}</p>}{working&&<p>{verified} / {r.artifacts.length} artifacts verified</p>}{["not_requested","failed"].includes(r.state)&&<button disabled={busy} className={primary} onClick={()=>void action("archive")}>{r.state==="failed"?"Retry Archive":"Archive Now"}</button>}{(missing||r.state==="restore_failed")&&<button disabled={busy||working} className={primary} onClick={()=>void action("restore")}>Restore &amp; Watch</button>}<ul className="space-y-1">{r.artifacts.map(a=><li key={a.local_object_key}>{a.role.replaceAll("_"," ")} · {a.verified?"Drive verified":"Not archived"} · {a.local_removed?"Local copy removed":"Local"}</li>)}</ul><p>{space(r.bytes_removed??0)} removed through managed cleanup</p>{r.manifest?.verified&&!working&&<details><summary className="cursor-pointer">Local cleanup</summary><label className="mt-3 block">Remove only verified media<select className="ml-3 rounded border p-2" value={policy} onChange={e=>setPolicy(e.target.value)}>{Object.entries(policies).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><p className="mt-3">{space(r.artifacts.filter(a=>!a.local_removed&&a.verified&&(policy==="cloud_only"||(policy==="restorable_media"&&a.role!=="final_video")||(policy==="intermediates"&&a.intermediate))).reduce((n,a)=>n+a.size,0))} known local media eligible. Each remote copy is reverified before removal.</p><button disabled={busy} className="mt-3 rounded border p-3" onClick={()=>void action("cleanup")}>Apply verified cleanup</button></details>}<details><summary>Diagnostics</summary><pre className="overflow-auto text-xs">{JSON.stringify(r,null,2)}</pre></details></>}</section>;
}
