import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { apiJson } from "../lib/apiClient";
import { ProjectsPage } from "./ProjectsPage";
import { SceneVideoPage } from "./SceneVideoPage";
vi.mock("../lib/apiClient",async original=>({...await original<typeof import("../lib/apiClient")>(),apiJson:vi.fn()}));
beforeEach(()=>{vi.mocked(apiJson).mockReset();});
function show(route='/scene-jobs/job') {const client=new QueryClient({defaultOptions:{queries:{retry:false,refetchOnWindowFocus:false}}});const view=render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[route]}><Routes><Route path="/" element={<ProjectsPage/>}/><Route path="/scene-jobs/:jobId" element={<SceneVideoPage/>}/></Routes></MemoryRouter></QueryClientProvider>);return {cleanup:()=>{view.unmount();client.clear();}};}
const project={id:'job',title:'Crystal Robot',display_status:'Needs review',next_action:{type:'review_scene',label:'Review Scene 1',message:'Watch the scene and decide whether to accept it.',scene_order:1,background:false},scene_count:2,accepted_count:0,updated_at:'2026-10-09T09:00:00Z',thumbnail_url:'/saved.png'};
const request={story_beat:'Discovery',scene_goal:'Find the crystal',action:'Walk into the workshop',entry_state:'Outside',exit_state:'Inside',character_continuity:'Same robot',environment_continuity:'Same room',visual_description:'Robot in workshop',motion_prompt:'FULL FLOW PROMPT',aspect_ratio:'16:9',duration_seconds:8,generation_attempt:1};
const review={verdict:'warning',summary:'FULL TECHNICAL AI SUMMARY',issues:[{category:'lighting',severity:'low',description:'Small lighting shift',evidence_frames:[]}],checks:{lighting:'warning'},retry_prompt_delta:[],frames:[{index:1,timestamp_seconds:0.5}]};
const reviewed={...project,status:'awaiting_human_decision',current_step:'awaiting_human_decision',generation_provider:'flow_web',review_policy:'ai_assisted',continuity_mode:'chained_frames',production:{started:true,paused:false,scene_count:2,accepted_count:0,current_scene:1,scenes:[{order:1,status:'awaiting_acceptance'},{order:2,status:'waiting'}]},scenes:[{order:1,status:'human_decision_required',clip_url:'/clip.mp4',current_attempt:1,generation_request:request,attempts:[{attempt:1,imported_at:'2026-10-09',review,review_runs:[{run_id:'r',status:'completed'}]}]},{order:2,status:'waiting',generation_request:{...request,story_beat:'Activation'}}]};

it('shows a useful first-run empty Projects state',async()=>{vi.mocked(apiJson).mockResolvedValue({projects:[],has_more:false});const view=show('/');expect(await screen.findByRole('heading',{name:'Create your first AI video'},{timeout:4000})).toBeInTheDocument();expect(screen.getByRole('link',{name:'New Video'})).toHaveAttribute('href','/videos/new');view.cleanup();});
it('shows title, thumbnail, friendly status, progress and next action',async()=>{vi.mocked(apiJson).mockResolvedValue({projects:[project],has_more:false});const view=show('/');const card=await screen.findByRole('article');expect(within(card).getByRole('heading',{name:'Crystal Robot'})).toBeInTheDocument();expect(within(card).getByText('Needs review')).toBeInTheDocument();expect(within(card).getByText(/0 \/ 2 scenes approved/)).toBeInTheDocument();expect(within(card).getByAltText('Crystal Robot preview')).toBeInTheDocument();expect(within(card).getByRole('link',{name:'Review Scene 1'})).toHaveAttribute('href','/scene-jobs/job');expect(apiJson).toHaveBeenCalledTimes(1);view.cleanup();});
it('resumes a project directly into review after page reload',async()=>{vi.mocked(apiJson).mockImplementation(async path=>path.startsWith('/scene-video-jobs?')?{projects:[project]}:reviewed);let view=show('/');await userEvent.click(await screen.findByRole('link',{name:'Review Scene 1'}));expect(await screen.findByRole('button',{name:'Accept Scene'})).toBeVisible();view.cleanup();view=show();expect(await screen.findByRole('button',{name:'Accept Scene'})).toBeVisible();expect(vi.mocked(apiJson).mock.calls.every(([,options])=>!options)).toBe(true);view.cleanup();});
it('puts video, story goal and advisory summary above collapsed diagnostics',async()=>{vi.mocked(apiJson).mockResolvedValue(reviewed);const view=show();expect(await screen.findByLabelText('Scene 1 video')).toBeVisible();expect(screen.getByText('Story goal: Walk into the workshop')).toBeVisible();expect(screen.getByText(/This scene starts a new video/)).toBeVisible();expect(screen.getAllByText('Small lighting shift')[0]).toBeVisible();expect(screen.getByRole('button',{name:'Regenerate'})).toBeVisible();expect(screen.getByRole('button',{name:'Accept Scene'})).toBeVisible();expect(screen.getByText('Full AI details').closest('details')).not.toHaveAttribute('open');expect(screen.getByText('Advanced / Diagnostics').closest('details')).not.toHaveAttribute('open');expect(screen.queryByText('Job ID')).not.toBeInTheDocument();view.cleanup();});
it('renders concise storyboard and exactly one Start Production action',async()=>{vi.mocked(apiJson).mockResolvedValue({...reviewed,next_action:{...project.next_action,type:'start_production',label:'Start Production'},production:{...reviewed.production,started:false},scenes:reviewed.scenes.map(scene=>({...scene,clip_url:undefined,attempts:undefined,current_attempt:undefined}))});const view=show();await screen.findByRole('heading',{name:'Storyboard'});expect(screen.getAllByRole('button',{name:'Start Production'})).toHaveLength(1);expect(screen.getAllByText('Scene details')[0].closest('details')).not.toHaveAttribute('open');expect(screen.getByRole('button',{name:'Regenerate Storyboard'})).toBeVisible();expect(screen.queryByRole('button',{name:'Accept Scene'})).not.toBeInTheDocument();view.cleanup();});
it('shows paused resume as primary and authorizes only on click',async()=>{vi.mocked(apiJson).mockResolvedValue({...reviewed,display_status:'Paused',next_action:{...project.next_action,type:'resume_production',label:'Resume Production'},production:{...reviewed.production,paused:true}});const view=show();const button=await screen.findByRole('button',{name:'Resume Production'});expect(apiJson).toHaveBeenCalledTimes(1);await userEvent.click(button);expect(apiJson).toHaveBeenCalledWith('/scene-video-jobs/job/production/resume',{method:'POST',body:undefined});view.cleanup();});
it('shows retry review recovery without generating another video',async()=>{vi.mocked(apiJson).mockResolvedValue({...reviewed,display_status:'Needs attention',next_action:{...project.next_action,type:'retry_ai_review',label:'Retry AI Review'},scenes:[{...reviewed.scenes[0],attempts:[{attempt:1,imported_at:'2026-10-09',review_runs:[{run_id:'r',status:'failed',failure:'provider timeout'}]}]}]});const view=show();await screen.findByRole('button',{name:'Retry AI review'});expect(screen.queryByRole('button',{name:'Accept Scene'})).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Retry AI review'}));expect(apiJson).toHaveBeenCalledWith('/scene-video-jobs/job/scenes/1/attempts/1/review/retry',{method:'POST'});expect(vi.mocked(apiJson).mock.calls.some(([path])=>path.includes('/flow/'))).toBe(false);view.cleanup();});
it('makes uncertain Flow recovery understandable without hidden browser calls',async()=>{vi.mocked(apiJson).mockResolvedValue({...reviewed,display_status:'Needs attention',next_action:{...project.next_action,type:'resolve_flow_attention',label:'Resolve Flow Attention',message:'Automatic retry is paused to avoid spending credits twice.'},scenes:[{...reviewed.scenes[0],clip_url:undefined,attempts:undefined,flow_runs:[{run_id:'f',status:'human_action_required',submission_intent:true}]}]});const view=show();expect(await screen.findByRole('link',{name:'Open Flow to Check'})).toBeVisible();expect(screen.getByText(/Automatic retry is paused/)).toBeVisible();expect(apiJson).toHaveBeenCalledTimes(1);view.cleanup();});
it('shows clean final playback, scene markers and original artifact download',async()=>{vi.mocked(apiJson).mockResolvedValue({...reviewed,status:'completed',display_status:'Completed',next_action:{...project.next_action,type:'watch_final_video',label:'Watch Final Video',scene_order:undefined},video_url:'/scene-video-jobs/job/artifacts/video',duration_seconds:16,aspect_ratio:'16:9',scene_boundaries:[{scene_order:1,start_seconds:0,end_seconds:8},{scene_order:2,start_seconds:8,end_seconds:16}]});const view=show();expect(await screen.findByRole('heading',{name:'Your video is ready'})).toBeVisible();expect(screen.getByLabelText('Final video video')).toBeVisible();expect(screen.getByRole('navigation',{name:'Scene markers'})).toBeVisible();expect(screen.getByRole('link',{name:'Download Video'}).getAttribute('href')).toMatch(/artifacts\/video\?download=1$/);expect(screen.queryByRole('button',{name:'Accept Scene'})).not.toBeInTheDocument();expect(screen.getByText(/View production details/).closest('details')).not.toHaveAttribute('open');view.cleanup();});
it('keeps older responses with missing product fields readable',async()=>{vi.mocked(apiJson).mockResolvedValue({id:'old',status:'completed',current_step:'completed',video_url:'/old.mp4',scenes:[]});const view=show();expect(await screen.findByLabelText('Final video video')).toBeInTheDocument();view.cleanup();});
it('keeps manual fallback discoverable in collapsed Advanced',async()=>{vi.mocked(apiJson).mockResolvedValue(reviewed);const view=show();await screen.findByRole('button',{name:'Accept Scene'});expect(screen.getByText('Advanced / Diagnostics · Manual Flow').closest('details')).not.toHaveAttribute('open');await userEvent.click(screen.getByText('Advanced / Diagnostics · Manual Flow'));expect(screen.getByRole('link',{name:'Open Google Flow'})).toBeVisible();expect(screen.queryByLabelText('Attach reference PNG (optional)')).not.toBeInTheDocument();view.cleanup();});

it('uses backend opening-image next action and keeps diagnostics collapsed',async()=>{vi.mocked(apiJson).mockResolvedValue({...reviewed,next_action:{...project.next_action,type:'review_opening_image',label:'Review Opening Image'},opening_image:{required:true,versions:[{version:1}]},opening_image_url:'/opening.png',scenes:reviewed.scenes.map(scene=>({...scene,clip_url:undefined,current_attempt:undefined,attempts:undefined}))});const view=show();expect(await screen.findByRole('button',{name:'Use This Image'})).toBeVisible();expect(screen.getByText('Advanced / Diagnostics').closest('details')).not.toHaveAttribute('open');expect(screen.queryByRole('button',{name:'Generate in Flow'})).not.toBeInTheDocument();expect(apiJson).toHaveBeenCalledTimes(1);view.cleanup();});

it('preserves the whole portrait preview on project cards',async()=>{vi.mocked(apiJson).mockResolvedValue({projects:[{...project,aspect_ratio:'9:16'}],has_more:false});const view=show('/');expect(await screen.findByAltText('Crystal Robot preview')).toHaveClass('object-contain');view.cleanup();});
it('keeps eight planned scenes compact with an eighty-second estimate and generation awareness',async()=>{vi.mocked(apiJson).mockResolvedValue({...reviewed,scene_count:8,scene_seconds:10,production:undefined,next_action:{type:'start_production',label:'Start Production',message:'Review the storyboard.',background:false},scenes:Array.from({length:8},(_,index)=>({order:index+1,status:'waiting',generation_request:{...request,duration_seconds:10,story_beat:`Beat ${index+1}`}}))});const view=show();const storyboard=await screen.findByLabelText('Storyboard');expect(storyboard).toHaveTextContent('~80 sec');expect(storyboard).toHaveTextContent('8 initial Flow video generations');expect(within(storyboard).getAllByText('Scene details')).toHaveLength(8);for(const details of within(storyboard).getAllByText('Scene details'))expect(details.closest('details')).not.toHaveAttribute('open');expect(screen.getByRole('button',{name:'Start Production'})).toBeVisible();expect(vi.mocked(apiJson).mock.calls.every(([,options])=>!options)).toBe(true);view.cleanup();});
